version: "3"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: tenant_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
